### ISSUE TITLE
Use a single template per-email and localise it within the template

### ISSUE THREAD

**Issue by ericlinagora** [linagora/twake-drive-legacy#691]
Currently e-mail templates exist in versions for en and fr. This ticket is about making a single template, and from within it calling translation labels (already available in the backend though rarely used).

related: #402

**Comment by Popokok** [comment]
Hi, I would like to work on this issue.

**Comment by ericlinagora** [comment]
Sure, welcome

**Comment by Popokok** [comment]
Hi. I'm pretty sure I know how to deal with this issue, but I ran into a problem. I can't find a way how to test it. Do you perhaps have any ideas?

**Comment by ericlinagora** [comment]
Hi, if this value https://github.com/linagora/twake-drive/blob/main/tdrive/backend/node/config/default.json#L114 is true, it should print emails in the logs. Heads up though, we're probably going to work on this soon too

**Comment by Popokok** [comment]
I got the value set as true, but I can't find the logs anywhere. I thought that those e-mails generate when user grants access to files in his drive to another user and I was trying to replicate it, but I couldn't figure it out, so I think I'm misunderstanding something.  Could you please specify when are those e-mails  generated and where can I find the logs of them being sent? 
Thank you.

**Comment by ericlinagora** [comment]
It seems we had a few bugs in the debug e-mail output, I fixed them in this commit https://github.com/linagora/twake-drive/pull/738/commits/fdccfa5f11ebd62e3e897e679aa6bf2de7d47a9e . Sorry about that.

**Comment by Popokok** [comment]
Are those logs supposed to be stdout, because I still can't see or find them anywhere.
